### ISSUE TITLE
Implement Zip streaming

### ISSUE THREAD

**Issue by Arno500** [DirectoryLister/DirectoryLister#1118]
### Directory Lister Version

3.12.3

### PHP Version

8.1

### Web Server

Apache

### Describe the Bug

The current Zip implementation is simple and universal (since this is using a native PHP class). But it has the following issues:
- Needs to buffer the whole Zip to a temporary file
- Waits for the Zip to be created, possibly creating timeouts when reverse proxies do not allow long requests (looking at you Cloudflare, but this is a bad practice to have long requests anyway)
- Takes necessarily at least the same time as a potential streaming implementation (because it needs to be compressed, then stored, then sent)
- Cannot control the compression (at least, not in the config as of now)

My proposition would be to use the [ZipStream-PHP](https://maennchen.dev/ZipStream-PHP/guide/Symfony.html) library, since they reimplemented the Zip specification in PHP compatible with streamed responses. A few details:
- The config will need to be updated
- The minimum PHP version will need to be bumped to 8.1
I imagined 3 possibilities:
1. Zip is disabled
2. Compressed Zip (deflate)
3. Uncompressed Zip (store)

For the 3., it would even be possible to estimate the size of the Zip, allowing the browser to display a proper progress (it is unfortunately not possible for compressed Zip for obvious reasons).
An interesting side effect to this would be that #1050 is no longer needed (at least for Zip files).
I volunteer for the implementation, but I just wanted to be sure those “details” are OK for the project. Are those acceptable?

Thank you for this project!

**Comment by PHLAK** [comment]
Streaming the Zip response is a good idea. I also like the option of compressed vs uncompressed Zips as well. However, bumping the minimum PHP version to 8.1 is a no-go.

Directory Lister aims to support all [currently supported PHP versions](https://www.php.net/supported-versions.php). This means we need to support PHP 8.0 until at least November of this year. Honestly, I even procrastinated on merging #1043 until today because I was hesitant to drop support for PHP 7.4, but it was time.

That being said, is there some way we can accomplish this without dropping PHP 8.0 support for now? Directory Lister is built on [Slim PHP](https://www.slimframework.com), maybe there's something in the framework that can help us with this?

Also, thank you for taking the time to discuss these changes in advanced. I'd like to support this feature and would have felt bad if you put in a lot of work that would need to be redone.

**Comment by Arno500** [comment]
Apparently there is nothing in Slim for that (https://discourse.slimframework.com/t/slim4-output-buffering-large-files-zip-streaming/4917).

The previous version used to support PHP 8.0 (so it's the 2.0 one). We are not losing many features, maybe just a better size estimation that was just implemented inside the code, but they put an example in their documentation for a basic one. And they  will still maintain it for bug fixes and security patches, so it seems a good middle ground for me.

You're welcome, I did this because I also wanted to not lose time and open the discussion on it!

**Comment by PHLAK** [comment]
Using the 2.X version of ZipStream-PHP seems like it will work.
