### ISSUE TITLE
Individual Branding/Labeling

### ISSUE THREAD

**Issue by rankerson** [DirectoryLister/DirectoryLister#325]
**Describe the solution you'd like**
I would like to have the possibility to add maybe a individual title of the page or an additional (small) image into the header or footer. Do you think sth. like this would be possible?

**Describe alternatives you've considered**
I tried to modify the "header.twig". Although it is not the best solution concerning updates etc. it didn't work and the changes have not been shown. Tried with several browsers and devices to  avoid any cache issue.

**Comment by PHLAK** [comment]
Tank you for the suggestion. Not sure if this is something we'll add but it will be considered.

> I tried to modify the "header.twig" ... it didn't work and the changes have not been shown.

This is likely due to the views being cached. Try removing all files in `app/cache` after you've made your changes.

    rm -rf app/cache/*

Additionally, while you're working on changes you can disable the view cache temporarily by setting the `VIEW_CACHE` option to `false` in your `.env` file.
