### ISSUE TITLE
DefaultRoot

### ISSUE THREAD

**Issue by Barraque** [DirectoryLister/DirectoryLister#554]
Duplicate of #25 because I think it's a really good feature.

I think, it's been a good feature, to add a config parameter, called default root.
In that line u can set the directory.

For example, i made a symlink near the index.php. I want only list this folder. And if i can set that, that would be great :D

**Comment by PHLAK** [comment]
Unfortunately configuring a different "base" directory is not currently possible. At the moment the Directory Lister code and files to be listed must be in the same folder.

This is due to the way Directory Lister handles (or rather doesn't handle) file access. Directory Lister only lists the files. When it comes to accessing (i.e. downloading) those files it defers to the web server to handle. While Directory Lister could list files outside of the web server's root folder the web server would not be able to access those files for download.

Someday in the future we may add file handling to Directory Lister which would allow this to be implemented but for now it's not in scope.

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
