### ISSUE TITLE
Not compatible with ie11

### ISSUE THREAD

**Issue by wloot** [DirectoryLister/DirectoryLister#566]
**Directory Lister Version**

**Site**

https://demo.directorylister.com/

**Describe the bug**

The loading animation will not disappear and whole page is unclickable.

![image](https://user-images.githubusercontent.com/30223095/107166996-a4a1c780-69f2-11eb-8a40-fe473c348d83.png)

**Additional context**

IE console says there is a error in app.js: https://docs.microsoft.com/en-us/scripting/javascript/misc/syntax-error-javascript

**Comment by PHLAK** [comment]
Thanks for bringing this to our attention. Will look into this when I can (not sure I have IE11 installed anywhere currently). Can you provide any additional information about the errors in the console?

**Side Note:** It looks like IE11 will be reaching end of life on August 17th, 2021. Depending on the amount of work work required to fix this we may not fix it.

**Comment by PHLAK** [comment]
Unfortunately this appears to be due to [Tailwind CSS not supporting IE11](https://tailwindcss.com/docs/browser-support). If you require IE11 support you can try a version that was on Tailwind CSS 1.X. I believe [v3.6.1](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.6.1) was the latest version that will support IE11.
