### ISSUE TITLE
[BUG] docker-compose isn't working

### ISSUE THREAD

**Issue by LimitlessGreen** [DirectoryLister/DirectoryLister#711]
**v3.9.0**

I tried to run DirectoryListener with the provided docker-compose.yaml file.

```
Warning: require(/var/www/html/app/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 7

Fatal error: Uncaught Error: Failed opening required '/var/www/html/app/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/index.php:7 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 7
```

**Comment by PHLAK** [comment]
The `docker-compose.yaml` file is intended for development only. If you wish to solve the error you must set up the development environment. See the [Development Environment](https://docs.directorylister.com/developers/development-environment) documentation for instructions on doing so.

More specifically, the error you're seeing is because the PHP dependencies have not been installed and must be installed with [Composer](https://getcomposer.org). You will also need to install the JavaScript dependencies and compile the assets as well (with [npm](https://nodejs.org/en/)).

**Comment by PHLAK** [comment]
FYI, starting with the [v5.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) an official Docker image is available. See the [Docker documentation](https://docs.directorylister.com/getting-started/docker) for more information.
