### ISSUE TITLE
DirectoryLister Fails to Hide Files in a Symbolic Link

### ISSUE THREAD

**Issue by Bubba8291** [DirectoryLister/DirectoryLister#755]
### Directory Lister Version

3.9.0

### PHP Version

7.2

### PHP Extensions

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### Web Server

Apache

### Describe the Bug

DirectoryLister fails to hide files in a symbolic link. For example, when I create a symbolic link to inside the document root, anything in that symbolic link directory will not be hidden if specified in the `.hidden` file or the `hidden_files` option in the `app.php` config file.

**Comment by PHLAK** [comment]
I wonder if this is because it's resolving the actual path of the file instead of the relative path to the installation directory. I will have to dig into this further.

If that's the case preceding the pattern with `**` may work. For example, assuming you have a file at `{{ INSTALLATION_PATH }}/some/path/foo.txt` try 

```
**/some/path/foo.txt
```

**Comment by Bubba8291** [comment]
I just tried it, and a few other ways like that. I had no luck with it. But I found a workaround for my scenario. I'm using rclone for the mount where the symbolic links go to. rclone has a feature where you can exclude files and directories, so I ended up using that. I still didn't figure out why the `.hidden` file wouldn't exclude items in a symbolic link though. So this issue is still up in the air.

**Comment by Teqed** [comment]
I've tried some combinations of wildcards as well to try and get past this but no luck. For example, if I wanted to hide *.txt files in any directory including symbolic links, I'd expect `**/*.txt` to work, but it only hides *.txt files in non-symbolic directories.

I'm using IIS and a junction made by MKLINK so my environment is different than Bubba8291's, but for the time being I've moved the files I wanted hidden elsewhere and may rework my file structure so that DirectoryLister can be installed to the same directory I want it to browse.
