### ISSUE TITLE
How do specify the directory I want to show?

### ISSUE THREAD

**Issue by TheGhost2804** [DirectoryLister/DirectoryLister#867]
I can't seem to find how to list a specific directory, is there no setting for that?

**Comment by PHLAK** [comment]
Unfortunately configuring a different "base" directory is not currently possible. At the moment the Directory Lister code and files to be listed must be in the same folder.

This is due to the way Directory Lister handles (or rather doesn't handle) file access. Directory Lister only lists the files. When it comes to accessing (i.e. downloading) those files it defers to the web server to handle. While Directory Lister could list files outside of the web server's root folder the web server would not be able to access those files for download.

To list a specific directory, upload the Directory Lister code to the directory you want to list.

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
