### ISSUE TITLE
How to get app to list a specific folder structure?

### ISSUE THREAD

**Issue by schizovivek** [DirectoryLister/DirectoryLister#920]
I've setup directorylister on lighttpd. Installed php version 7.4 and also the xml and zip plugins. When I launch directory lister it gives a blank page. How to tell the app which folder to list?

**Comment by PHLAK** [comment]
Unfortunately configuring a different "base" directory is not currently possible. The Directory Lister code and files to be listed must be in the same folder.

This is due to the way Directory Lister handles (or rather doesn't handle) file access. Directory Lister only lists the files. When it comes to accessing (i.e. downloading) those files it defers to the web server to handle. While Directory Lister could list files outside of the web server's root folder the web server would not be able to access those files for download.

Someday in the future we may add file handling to Directory Lister which would allow this to be implemented but for now it's not in scope.

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
